apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  parentRefs: 
  - name: localhost
    sectionName: https
    port: 8443
  hostnames: 
  - mail.localhost
  rules: 
  - backendRefs:
    - name: {{ include "chart.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: 8080
  # - matches:
  #   - path: 
  #       value: "/admin"
  #       type: PathPrefix
  #   backendRefs:
  #   - name: {{ include "chart.fullname" . }}
  #     namespace: {{ .Release.Namespace }}
  #     port: 8080
  # - matches:
  #   - path: 
  #       value: "/"
  #       type: PathPrefix
  #   backendRefs:
  #   - name: {{ include "chart.fullname" . }}
  #     namespace: {{ .Release.Namespace }}
  #     port: 80
