apiVersion: v1
kind: PersistentVolume
metadata:
  name: stalwart-pv
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: DirectoryOrCreate