image:
  repository: ghcr.io/advplyr/audiobookshelf
  pullPolicy: IfNotPresent
  tag: "2.35.1"

volumes:
  audiobooks:
    hostPath: "/Users/jimtang/Music/audiobooks"
  podcasts:
    hostPath: "/Users/jimtang/Music/podcasts"
  config:
    hostPath: "/Users/jimtang/Development/vol/audiobookshelf/config"
  metadata:
    hostPath: "/Users/jimtang/Development/vol/audiobookshelf/metadata"

service:
  enabled: true

httproute:
  enabled: true
