apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ include "chart.fullname" . }}-edge
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    hostname: "edge"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  logging:
    level:
      default: info
  telemetry:
    metrics:
      prometheus:
        disable: false
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        name: {{ include "chart.fullname" . }}-edge

---