apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "chart.fullname" . }}-edge
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    hostname: "edge"
  annotations:
    # "helm.sh/hook": post-install,post-upgrade
spec:
  gatewayClassName: {{ include "chart.fullname" . }}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: {{ include "chart.fullname" . }}-edge
  listeners:
  #
  # *.localhost
  #
  - name: http-localhost
    port: 80
    protocol: HTTP
    hostname: "*.localhost"
  - name: tls-localhost
    port: 443
    protocol: TLS
    hostname: "*.localhost"
    tls:
      mode: Passthrough
  - name: http-localhost-apex
    port: 80
    protocol: HTTP
    hostname: "localhost"
  - name: tls-localhost-apex
    port: 443
    protocol: TLS
    hostname: "localhost"
    tls:
      mode: Passthrough
  #
  # jimtang.me
  #
  - name: http-jimtang-me
    port: 80
    protocol: HTTP
    hostname: "jimtang.me"
  - name: tls-jimtang-me
    port: 443
    protocol: TLS
    hostname: "jimtang.me"
    tls:
      mode: Passthrough
  #
  # lab9.studio
  # 
  - name: http-lab9-studio
    port: 80
    protocol: HTTP
    hostname: "lab9.studio"
  - name: tls-lab9-studio
    port: 443
    protocol: TLS
    hostname: "lab9.studio"
    tls:
      mode: Passthrough

--- 