apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jackett.fullname" . }}
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jackett.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jackett.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "jackett.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: jackett
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            {{- range $name, $port := .Values.service.ports }}
            - containerPort: {{ $port.port }}
              name: {{ $name }}
            {{- end }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range $name, $volume := .Values.persistence }}
            {{- if $volume.enabled }}
            - name: {{ $name }}
              mountPath: {{ $volume.mountPath }}
            {{- end }}
            {{- end }}

      volumes:
        {{- range $name, $volume := .Values.persistence }}
        {{- if $volume.enabled }}
        - name: {{ $name }}
          persistentVolumeClaim:
            claimName: {{ include "jackett.fullname" $ }}-{{ $name }}
        {{- end }}
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}