{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jackett.fullname" $ }}
  labels:
    {{- include "jackett.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jackett.selectorLabels" $ | nindent 4 }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - name: {{ $name }}
      port: {{ $port.port }}
      protocol: {{ $port.protocol }}
    {{- end }}
{{- end }}