apiVersion: v2
name: postgresql
description: PostgreSQL on local cluster
type: application
version: 0.1.0
appVersion: "18.7.11"
dependencies:
  - name: postgresql
    version: "18.7.11"
    repository: ""
