# bases:
# - environments.yaml
#
helmDefaults:
  cleanupOnFail: true
  createNamespace: true
  forceConflicts: true
  serverSide: "true"
  skipCRDs: false
  skipDeps: true
  skipRefresh: true
  takeOwnership: true

commonLabels:
  helm.sh/installed-by: helmfile

releases:
  #
  # ns:default
  #
  - name: secrets
    chart: ./secrets
    installed: true
    values:
      - ./secrets/values-local.yaml
    labels:
      group: config

  - name: cert-manager
    chart: ./cert-manager
    suppressDiff: true
    installed: true
    values:
      - reIssue: false
      - ./cert-manager/values.yaml
      - ./cert-manager/values-local.yaml
    labels:
      name: cert-manager
      group: gateway

  - name: elastic
    chart: ./elastic
    installed: false
    values:
      - ./elastic/values.yaml
      - ./elastic/values-local.yaml
    labels:
      name: elastic
      group: log

  - name: envoy
    chart: ./envoy
    installed: true
    suppressDiff: true
    values:
      - ./envoy/values.yaml
      - ./envoy/values-local.yaml
    labels:
      group: gateway

  - name: fluent-bit
    chart: ./fluent-bit
    values:
      - ./fluent-bit/values.yaml
      - ./fluent-bit/values-local.yaml
    installed: false
    labels:
      group: log

  - name: lgtm
    chart: ./lgtm
    values:
      - ./lgtm/values.yaml
      - ./lgtm/values-local.yaml
    installed: true
    labels:
      group: log

  - name: kafka
    chart: ./kafka
    installed: true
    values:
      - ./kafka/values.yaml
      - ./kafka/values-local.yaml
    labels:
      name: kafka

  - name: keycloak
    chart: ./keycloak
    installed: true
    values:
      - ./keycloak/values.yaml
      - ./keycloak/values-local.yaml
    labels:
      name: keycloak
      group: auth

  - name: postgresql
    chart: ./postgresql
    installed: true
    values:
      - ./postgresql/values.yaml
      - ./postgresql/values-local.yaml
    labels:
      name: postgresql

  - name: prometheus
    chart: ./prometheus
    installed: false
    labels:
      name: prometheus
      group: log
    values:
      - ./prometheus/values.yaml

  - name: redis
    chart: ./redis
    installed: true
    values:
      - ./redis/values.yaml
      - ./redis/values-local.yaml
    labels:
      name: redis

  - name: stalwart
    chart: ./stalwart
    installed: false
    values:
      - ./stalwart/values.yaml
      - ./stalwart/values-local.yaml
    suppressDiff: true
    labels:
      name: stalwart
      group: mail
  #
  # ns:apps
  #
  - name: audiobooks
    chart: ./audiobooks
    namespace: apps
    installed: true
    values:
      - ./audiobooks/values.yaml
      - ./audiobooks/values-local.yaml
    labels:
      name: audiobooks
      group: apps

  - name: torrents
    chart: ./torrents
    namespace: apps
    installed: true
    values:
      - ./torrents/values.yaml
      - ./torrents/values-local.yaml
    labels:
      name: torrents
      group: apps

  - name: headlamp
    chart: ./headlamp
    namespace: apps
    installed: true
    values:
      - ./headlamp/values.yaml
      - ./headlamp/values-local.yaml
    labels:
      name: headlamp
      group: headlamp

  - name: headlamp-oauth2-proxy
    chart: ./oauth2-proxy
    namespace: apps
    installed: true
    values:
      - ./oauth2-proxy/values.yaml
      - ./oauth2-proxy/values-headlamp.yaml
    labels:
      name: oauth2-proxy-headlamp
      group: headlamp

  - name: pgadmin
    chart: ./pgadmin
    namespace: apps
    installed: true
    values:
      - ./pgadmin/values.yaml
      - ./pgadmin/values-local.yaml
    labels:
      name: pgadmin

  - name: redis-insight
    chart: ./redis-insight
    namespace: apps
    installed: true
    values:
      - ./redis-insight/values.yaml
      - ./redis-insight/values-local.yaml
    labels:
      name: redis-insight
  #
  # ns:dev
  #
  - name: flux
    chart: ./flux
    namespace: dev
    installed: true
    values:
      - ./flux/values.yaml
      - ./flux/values-local.yaml
    labels:
      name: flux

  # nginx for dev app file serve
  - name: nginx-app
    chart: ./nginx
    namespace: dev
    installed: true
    values:
      - ./nginx/values.yaml
      - ./nginx/values-app.yaml
    labels:
      name: nginx-app
      group: nginx-app

  - name: nginx-app-oauth2-proxy
    chart: ./oauth2-proxy
    namespace: dev
    installed: true
    values:
      - ./oauth2-proxy/values.yaml
      - ./oauth2-proxy/values-nginx-app.yaml
    labels:
      name: oauth2-proxy-nginx-app
      group: nginx-app

  # nginx for public landing page
  - name: nginx-public
    chart: ./nginx
    namespace: dev
    installed: true
    values:
      - ./nginx/values.yaml
      - ./nginx/values-public.yaml
    labels:
      name: nginx-public

  # nginx for static file serve
  - name: nginx-static
    chart: ./nginx
    namespace: dev
    installed: true
    values:
      - ./nginx/values.yaml
      - ./nginx/values-static.yaml
    labels:
      name: nginx-static
