{{- range $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name | quote }}
  namespace: {{ $secret.namespace | quote }}
  {{- with $secret.annotations }}
  annotations:
{{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
  {{- end }}
type: {{ default "Opaque" $secret.type | quote }}
stringData:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
