{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "headlamp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: envoy
    namespace: ingress
    sectionName: https
    port: 443
  hostnames:
  - headlamp.localhost
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    filters: []
    backendRefs:
    - name: {{ include "headlamp.fullname" . }}
      namespace: {{ .Release.Namespace }}
      port: 80
      weight: 1
---
{{- end }}