eck-stack:
  enabled: true
  namespaceOverride: ""

  eck-elasticsearch:
    enabled: true
    fullnameOverride: elasticsearch

  eck-kibana:
    enabled: true
    elasticsearchRef:
      name: elasticsearch

  eck-agent:
    enabled: false

  eck-fleet-server:
    enabled: false

  eck-beats:
    enabled: false

  eck-logstash:
    enabled: false

  eck-apm-server:
    enabled: false

  eck-enterprise-search:
    enabled: false

  eck-autoops-agent-policy:
    enabled: false

  eck-package-registry:
    enabled: false

  extraObjects: []

