httproutes:
- name: grafana
  parentRefs:
  - name: envoy-localhost
    namespace: default
    sectionName: https
    port: 8443
  hostnames:
  - grafana.localhost
  rules:
  - backendRefs:
    - name: prometheus-grafana
      port: 80
- name: alertmanager
  parentRefs:
  - name: envoy-localhost
    namespace: default
    sectionName: https
    port: 8443
  hostnames:
  - alertmanager.localhost
  rules:
  - backendRefs:
    - name: prometheus-alertmanager
      port: 9093

prometheus:
  alertmanager:
    enabled: false

  grafana:
    enabled: true

    adminUser: admin

    admin:
      existingSecret: ""
      userKey: admin-user
      passwordKey: admin-password

    serviceMonitor:
      enabled: true

  kubernetesServiceMonitors:
    enabled: true

  kubeApiServer:
    enabled: true
    serviceMonitor:
      enabled: true

  kubelet:
    enabled: true
    namespace: kube-system

    serviceMonitor:
      enabled: true
      kubelet: true

  kubeControllerManager:
    enabled: true

    service:
      enabled: true
      port: null
      targetPort: null

    serviceMonitor:
      enabled: true
      interval: ""

      sampleLimit: 0

      targetLimit: 0

      labelLimit: 0

      labelNameLengthLimit: 0

      labelValueLengthLimit: 0

      proxyUrl: ""

      port: http-metrics

      jobLabel: jobLabel
      selector: {}

      https: null

      insecureSkipVerify: null

      serverName: null

      metricRelabelings: []

      relabelings: []

      additionalLabels: {}

      targetLabels: []

  coreDns:
    enabled: true
    service:
      enabled: true
      port: 9153
      targetPort: 9153

      ipDualStack:
        enabled: false
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"
    serviceMonitor:
      enabled: true
      interval: ""

      sampleLimit: 0

      targetLimit: 0

      labelLimit: 0

      labelNameLengthLimit: 0

      labelValueLengthLimit: 0

      proxyUrl: ""

      port: http-metrics

      jobLabel: jobLabel
      selector: {}

      metricRelabelings: []

      relabelings: []

      additionalLabels: {}

      targetLabels: []

      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubeDns:
    enabled: false
    service:
      dnsmasq:
        port: 10054
        targetPort: 10054
      skydns:
        port: 10055
        targetPort: 10055
      ipDualStack:
        enabled: false
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"
    serviceMonitor:
      interval: ""

      sampleLimit: 0

      targetLimit: 0

      labelLimit: 0

      labelNameLengthLimit: 0

      labelValueLengthLimit: 0

      proxyUrl: ""

      jobLabel: jobLabel
      selector: {}

      metricRelabelings: []

      relabelings: []

      dnsmasqMetricRelabelings: []

      dnsmasqRelabelings: []

      additionalLabels: {}

      targetLabels: []

      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubeEtcd:
    enabled: true

    endpoints: []

    service:
      enabled: true
      port: 2381
      targetPort: 2381
      ipDualStack:
        enabled: false
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"

    serviceMonitor:
      enabled: true
      interval: ""

      sampleLimit: 0

      targetLimit: 0

      labelLimit: 0

      labelNameLengthLimit: 0

      labelValueLengthLimit: 0

      proxyUrl: ""
      scheme: http
      insecureSkipVerify: false
      serverName: ""
      caFile: ""
      certFile: ""
      keyFile: ""

      port: http-metrics

      jobLabel: jobLabel
      selector: {}

      metricRelabelings: []

      relabelings: []

      additionalLabels: {}

      targetLabels: []

      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubeScheduler:
    enabled: true

    jobNameOverride: ""

    endpoints: []

    service:
      enabled: true
      port: null
      targetPort: null
      ipDualStack:
        enabled: false
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"

    serviceMonitor:
      enabled: true
      interval: ""

      sampleLimit: 0

      targetLimit: 0

      labelLimit: 0

      labelNameLengthLimit: 0

      labelValueLengthLimit: 0

      proxyUrl: ""
      https: null

      port: http-metrics

      jobLabel: jobLabel
      selector: {}

      insecureSkipVerify: null

      serverName: null

      metricRelabelings: []

      relabelings: []

      additionalLabels: {}

      targetLabels: []

  kubeProxy:
    enabled: true

    jobNameOverride: ""

    endpoints: []

    service:
      enabled: true
      port: 10249
      targetPort: 10249
      ipDualStack:
        enabled: false
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"

    serviceMonitor:
      enabled: true
      interval: ""

      sampleLimit: 0

      targetLimit: 0

      labelLimit: 0

      labelNameLengthLimit: 0

      labelValueLengthLimit: 0

      proxyUrl: ""

      port: http-metrics

      jobLabel: jobLabel
      selector: {}

      https: false

      metricRelabelings: []

      relabelings: []

      additionalLabels: {}

      targetLabels: []

      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubeStateMetrics:
    enabled: true

  kube-state-metrics:
    releaseLabel: true

    prometheusScrape: false

    prometheus:
      monitor:
        enabled: true

        http:
          honorLabels: true

        metrics:
          honorLabels: true

  nodeExporter:
    enabled: false
    operatingSystems:
      linux:
        enabled: true
      aix:
        enabled: true
      darwin:
        enabled: true

    forceDeployDashboards: false

  prometheus-node-exporter:
    namespaceOverride: ""
    service:
      portName: http-metrics
      ipDualStack:
        enabled: false
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"
      labels:
        jobLabel: node-exporter

    prometheus:
      monitor:
        enabled: false

        jobLabel: jobLabel

        interval: ""

        sampleLimit: 0

        targetLimit: 0

        labelLimit: 0

        labelNameLengthLimit: 0

        labelValueLengthLimit: 0

        scrapeTimeout: ""

        proxyUrl: ""

        metricRelabelings: []

        relabelings: []

      podMonitor:
        enabled: false

        jobLabel: jobLabel

  prometheusOperator:
    enabled: true

    service:
      annotations: {}
      labels: {}
      clusterIP: ""
      ipDualStack:
        enabled: false
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"

      nodePort: 30080

      nodePortTls: 30443

      additionalPorts: []

      loadBalancerIP: ""
      loadBalancerSourceRanges: []

      externalTrafficPolicy: Cluster

      type: ClusterIP

      externalIPs: []

    serviceMonitor:
      selfMonitor: true

      additionalLabels: {}

      interval: ""

      sampleLimit: 0

      targetLimit: 0

      labelLimit: 0

      labelNameLengthLimit: 0

      labelValueLengthLimit: 0

      scrapeTimeout: ""

      metricRelabelings: []

      relabelings: []

  prometheus:
    enabled: true

    agentMode: false

    annotations: {}

    additionalLabels: {}

    service:
      enabled: true
      annotations: {}
      labels: {}
      clusterIP: ""
      ipDualStack:
        enabled: false
        ipFamilies: ["IPv6", "IPv4"]
        ipFamilyPolicy: "PreferDualStack"

      port: 9090

      targetPort: 9090

      reloaderWebPort: 8080

      reloaderWebNodePort: null

      externalIPs: []

      nodePort: 30090

      loadBalancerIP: ""
      loadBalancerSourceRanges: []

      externalTrafficPolicy: Cluster

      type: ClusterIP

      additionalPorts: []

      publishNotReadyAddresses: false

      sessionAffinity: None

      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800

    serviceMonitor:
      selfMonitor: true

      interval: ""

      additionalLabels: {}

      sampleLimit: 0

      targetLimit: 0

      labelLimit: 0

      labelNameLengthLimit: 0

      labelValueLengthLimit: 0

      scheme: ""

      tlsConfig: {}

      bearerTokenFile:

      metricRelabelings: []

      relabelings: []

      additionalEndpoints: []