{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "chart.fullname" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: envoy-localhost
    namespace: net
    sectionName: https
    port: 8443
  hostnames:
  - audiobook.localhost
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    filters: []
    backendRefs:
    - name: {{ include "chart.fullname" . }}
      namespace:  {{ .Release.Namespace }}
      port: 80
      weight: 1
---
{{- end }}