apiVersion: v2
name: audiobookshelf
description: A chart for audiobookshelf server
type: application
version: 0.0.6
appVersion: "2.36.1"
home: https://github.com/jimtang2/helm-charts/tree/main/charts/audiobookshelf
sources:
  - https://github.com/advplyr/audiobookshelf
maintainers:
  - name: jimtang2
    url: https://github.com/jimtang2