apiVersion: v2
name: audiobookshelf
description: Audiobookshelf application chart
type: application
version: 0.2.0
appVersion: "2.35.1"
home: https://github.com/jimtang2/helm-charts/tree/main/charts/audiobookshelf
sources:
  - https://github.com/jimtang2/audiobookshelf
  - https://github.com/advplyr/audiobookshelf
maintainers:
  - name: jimtang2
    url: https://github.com/jimtang2