enabled: true

replicaCount: 1

image:
  repository: ghcr.io/advplyr/audiobookshelf
  tag: "2.35.1"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  enabled: true
  type: ClusterIP
  port: 80

persistence:
  # annotations on corresponding PVC are handy :)
  audiobooks:
    enabled: true
    accessModes: [ReadWriteOnce]
    size: 10Gi
    mountPath: /audiobooks
    storageClass: ""
    annotations: {}
  podcasts:
    enabled: true
    accessModes: [ReadWriteOnce]
    size: 10Gi
    mountPath: /podcasts
    storageClass: ""
    annotations: {}
  config:
    enabled: true
    accessModes: [ReadWriteOnce]
    size: 1Gi
    mountPath: /config
    storageClass: ""
    annotations: {}
  metadata:
    enabled: true
    accessModes: [ReadWriteOnce]
    size: 5Gi
    mountPath: /metadata
    storageClass: ""
    annotations: {}

env:
  - name: TZ
    value: UTC

probes:
  liveness:
    httpGet:
      path: /
      port: http
  readiness:
    httpGet:
      path: /
      port: http

resources: 
  limits:
    memory: 512Mi
    cpu: 1
securityContext: {}
podSecurityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}

gateway:
  enabled: false
  parentRefs: []
  hostnames: []