{{- define "cleanup.annotations" }}
"helm.sh/hook": pre-install,pre-upgrade
"helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}
---
{{- if default false .Values.reIssue }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-cleanup"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- include "cleanup.annotations" . | nindent 4 }}
    "helm.sh/hook-weight": "10"
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-cert-manager-bootstrap
      restartPolicy: Never
      containers:
      - name: cleanup
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          NAMESPACE="{{ .Release.Namespace }}"
          SELECTOR="app.kubernetes.io/instance={{ .Release.Name }}"
          TIMEOUT=60s
          echo "Deleting ClusterIssuers..."
          kubectl get clusterissuer \
            -l $SELECTOR \
            --ignore-not-found \
            -o name | xargs kubectl delete --timeout=$TIMEOUT || true
          
          echo "Deleting Certificates..."
          kubectl get certificates \
            -n $NAMESPACE \
            -l $SELECTOR \
            --ignore-not-found \
            -o name | xargs kubectl delete -n $NAMESPACE --timeout=$TIMEOUT || true
          
          echo "Cleanup done"
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
      activeDeadlineSeconds: 30
---
{{- end }}
