apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-edge-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-edge-gateway
      app.kubernetes.io/instance: envoy
  endpoints:
    - port: metrics
      interval: 30s
      path: /stats/prometheus

---