# bases:
# - environments.yaml

helmDefaults:
  cleanupOnFail: true
  createNamespace: true
  forceConflicts: true
  serverSide: true
  skipCRDs: false
  skipDeps: true
  skipRefresh: true
  takeOwnership: true

commonLabels:
  install: helmfile

releases:
  #
  # ns:default
  #
  - name: cert-manager
    chart: ./cert-manager
    values:
    - ./cert-manager/values.yaml
    - ../values/cert-manager.yaml
    - reIssue: false
    suppressDiff: true
    installed: true

  - name: elastic
    chart: ./elastic
    installed: false
    values:
    - ./elastic/values.yaml
    - ../values/elasticsearch.yaml

  - name: envoy
    chart: ./envoy
    installed: true
    suppressDiff: true
    values:
    - ./envoy/values.yaml
    - ../values/envoy.yaml

  - name: fluent-bit
    chart: ./fluent-bit
    values:
    - ./fluent-bit/values.yaml
    - ../values/fluent-bit.yaml
    installed: false

  - name: flux
    chart: ./flux
    installed: false

  - name: kafka
    chart: ./kafka
    installed: false
    values:
    - ./kafka/values.yaml
    - ../values/kafka.yaml

  - name: keycloak
    chart: ./keycloak
    values:
    - ./keycloak/values.yaml
    - ../values/keycloak.yaml
    installed: true
    needs:
    - postgresql

  - name: pgadmin
    chart: ./pgadmin
    installed: true
    values:
    - ./pgadmin/values.yaml
    - ../values/pgadmin.yaml
    needs:
    - postgresql

  - name: postgresql
    chart: ./postgresql
    installed: true
    values:
    - ./postgresql/values.yaml
    - ../values/postgresql.yaml

  - name: prometheus
    chart: ./prometheus
    installed: false

  - name: redis
    chart: ./redis
    installed: true
    values:
    - ./redis/values.yaml
    - ../values/redis.yaml

  - name: redis-insight
    chart: ./redis-insight
    installed: true
    values:
    - ./redis-insight/values.yaml
    - ../values/redis-insight.yaml

  - name: stalwart
    chart: ./stalwart
    installed: false
    values:
    - ./stalwart/values.yaml
    - ../values/stalwart.yaml
    suppressDiff: true
  #
  # ns:internal
  #
  - name: audiobooks
    chart: ./audiobooks
    namespace: internal
    installed: true
    values:
    - ./audiobooks/values.yaml
    - ../values/audiobookshelf.yaml

  - name: headlamp
    chart: ./internal/headlamp
    namespace: internal
    installed: false

  - name: nginx-internal
    chart: ./nginx
    namespace: internal
    values:
    - ./nginx/values.yaml
    - ../values/nginx-internal.yaml
    installed: true

  - name: torrents
    chart: ./torrents
    namespace: internal
    installed: true
    values:
    - ./torrents/values.yaml
    - ../values/torrents.yaml
  #
  # ns:public
  #
  - name: nginx-public
    chart: ./nginx
    namespace: public
    values:
    - ./nginx/values.yaml
    - ../values/nginx-public.yaml
    installed: true
