helmDefaults:
  createNamespace: true
  skipCRDs: false
  skipDeps: true
  skipRefresh: true
  cleanupOnFail: true
  takeOwnership: true
  forceConflicts: true
  serverSide: true

commonLabels:
  install: helmfile

releases:
  #
  # default
  #
  - name: kafka
    chart: ./kafka
    condition: enabled
    installed: false
  - name: postgresql
    chart: ./postgresql
    condition: enabled
    installed: false
  - name: elastic
    chart: ./elastic
    condition: enabled
    installed: false
  - name: stalwart
    chart: ./stalwart
    condition: enabled
    installed: false
  - name: prometheus
    chart: ./prometheus
    condition: enabled
    installed: false
  - name: fluent
    chart: ./fluent
    condition: enabled
    installed: false
  - name: cert-manager
    chart: ./cert-manager
    hooks:
    - events: ["prepare"]
      showlogs: true
      command: ./cert-manager/files/add_secrets.sh
      args: []
    condition: enabled
    installed: false
  - name: envoy
    chart: ./envoy
    condition: enabled
    installed: false
  - name: oauth2-proxy
    chart: ./oauth2-proxy
    condition: enabled
    installed: false
  - name: keycloak
    chart: ./keycloak
    condition: enabled
    installed: false
  - name: flux
    chart: ./flux
    condition: enabled
    installed: false
  - name: jaeger
    chart: ./jaeger
    condition: enabled
    installed: false
  #
  # internal
  #
  - name: audiobooks
    chart: ./internal/audiobooks
    namespace: internal
    condition: enabled
    installed: false
  - name: torrents
    chart: ./internal/torrents
    namespace: internal
    condition: enabled
    installed: false
  - name: headlamp
    chart: ./internal/headlamp
    namespace: internal
    condition: enabled
    installed: false
  - name: nginx
    chart: ./internal/nginx
    namespace: internal
    condition: enabled
    installed: false
  #
  # public
  #
  - name: nginx
    chart: ./public/nginx
    namespace: public
    condition: enabled
    installed: false
  