# bases:
# - environments.yaml

helmDefaults:
  createNamespace: true
  skipCRDs: false
  skipDeps: true
  skipRefresh: true
  cleanupOnFail: true
  takeOwnership: true
  forceConflicts: true
  serverSide: true

commonLabels:
  install: helmfile

releases:
  #
  # ns:default
  #
  - name: envoy
    chart: ./envoy
  - name: cert-manager
    chart: ./cert-manager
    values:
    - reIssue: false
  - name: postgresql
    chart: ./postgresql
  - name: elastic
    chart: ./elastic
  - name: prometheus
    chart: ./prometheus
  - name: fluent-bit
    chart: ./fluent-bit
    values:
    - ./fluent-bit/values.yaml
    - ../values/fluent-bit.yaml
  - name: keycloak
    chart: ./keycloak
  # - name: kafka
  #   chart: ./kafka
  # - name: redis
  #   chart: ./redis
  # - name: stalwart
  #   chart: ./stalwart
  #   condition: enabled
  #   installed: false
  # - name: oauth2-proxy
  #   chart: ./oauth2-proxy
  # - name: flux
  #   chart: ./flux
  # - name: jaeger
  #   chart: ./jaeger
  #
  # ns:internal
  #
  - name: audiobooks
    chart: ./audiobooks
    namespace: internal
  - name: torrents
    chart: ./torrents
    namespace: internal
  - name: nginx-internal
    chart: ./nginx
    namespace: internal
    values:
    - ./nginx/values.yaml
    - ../values/nginx-internal.yaml
  # - name: headlamp
  #   chart: ./internal/headlamp
  #   namespace: internal
  #
  # ns:public
  #
  - name: nginx-public
    chart: ./nginx
    namespace: public
    values:
    - ./nginx/values.yaml
    - ../values/nginx-public.yaml
