apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elastic
  hostPath:
    path: {{ .Values.volumes.elasticsearch.hostPath }}
    type: DirectoryOrCreate