enabled: true

image:
  repository: ghcr.io/advplyr/audiobookshelf
  pullPolicy: IfNotPresent
  tag: "2.35.1"

volumes:
  audiobooks:
    hostPath: ""
  podcasts:
    hostPath: ""
  config:
    hostPath: ""
  metadata:
    hostPath: ""

service:
  enabled: true

httproute:
  enabled: true
