apiVersion: v2
name: jackett
description: A chart for Jackett torrent proxy server
type: application
version: 0.0.1
appVersion: "0.24.2631"

home: https://github.com/jimtang2/helm-charts/tree/main/charts/jackett
sources:
  - https://github.com/Jackett/Jackett
maintainers:
  - name: jimtang2
    url: https://github.com/jimtang2