apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: eck-stack-eck-kibana-kb-http-tls
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: eck-stack-eck-kibana-kb-http
    sectionName: https
  validation:
    caCertificateRefs:
    - group: ""
      kind: Secret
      name: eck-stack-eck-kibana-kb-http-certs-public
    hostname: eck-stack-eck-kibana-kb-http.{{ .Release.Namespace }}.svc
---