apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: envoy-localhost
      namespace: net
      sectionName: https
      port: 8443
  hostnames:
    - kibana.localhost
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: eck-stack-eck-kibana-kb-http
        port: 5601
        weight: 1