---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgresql.primary.persistence.volumeName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/keep-policy: keep
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
  hostPath:
    path: {{ .Values.volumes.pgdata.hostPath }}
    type: DirectoryOrCreate
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.postgresql.primary.persistence.volumeName }}
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.primary.persistence.volumeName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-hostpath
  # volumeName: {{ .Release.name }}
