apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.secret.auth.password | b64enc }}
  postgres-password: {{ .Values.secret.auth.postgresPassword | b64enc }}
  replication-password: {{ .Values.secret.auth.replicationPassword | b64enc }}
