{{- range $name, $volume := .Values.persistence }}
{{- if $volume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbt.fullname" $ }}-{{ $name }}
  labels:
    {{- include "qbt.labels" $ | nindent 4 }}
  annotations:
    {{- with $volume.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml $volume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $volume.size | quote }}
  storageClassName: {{ $volume.storageClass | default $.Values.defaultStorageClass | quote }}
---
{{- end }}
{{- end }}