volumes:
  pgdata:
    hostPath: /Users/jimtang/Development/vol/postgresql

tcproute:
  enabled: true

postgresql:
  global:
    postgresql:
      fullnameOverride: ""
      auth:
        enablePostgresUser: true
        ## @param global.postgresql.auth.existingSecret Name of existing secret to use for PostgreSQL credentials (overrides `auth.existingSecret`).
        existingSecret: postgresql
        username: "postgres"
        database: "local"
        secretKeys:
          adminPasswordKey: ""
          userPasswordKey: ""
          replicationPasswordKey: ""
          metricsPasswordKey: ""
      ## @param global.postgresql.service.ports.postgresql PostgreSQL service port (overrides `service.ports.postgresql`)
      ##
      service:
        ports:
          postgresql: 5432

  # architecture: replication
  architecture: standalone

  diagnosticMode:
    enabled: false

  replication:
    ## @param replication.synchronousCommit Set synchronous commit mode. Allowed values: `on`, `remote_apply`, `remote_write`, `local` and `off`
    synchronousCommit: "off"
    numSynchronousReplicas: 0
    applicationName: postgresql_replica

  containerPorts:
    postgresql: 5432

  ldap:
    enabled: false

  postgresqlDataDir: /bitnami/postgresql/data

  tls:
    enabled: false
    autoGenerated: true
    certFilename: ""
    certKeyFilename: ""
    certCAFilename: ""
    crlFilename: ""
    ## @param tls.sslMode SSL mode to use when connecting to PostgreSQL. Applied to backup CronJob and password-update Job.
    ## Accepted values: disable, allow, prefer, require, verify-ca, verify-full
    ## ref: https://www.postgresql.org/docs/current/libpq-ssl.html
    ##
    sslMode: "verify-ca"

  primary:
    name: ""
    ## @param primary.configuration PostgreSQL Primary main configuration to be injected as ConfigMap
    ## ref: https://www.postgresql.org/docs/current/static/runtime-config.html
    ##
    # configuration: ""
    existingExtendedConfigmap: postgresql-extended-config
    ## @param primary.pgHbaConfiguration PostgreSQL Primary client authentication configuration
    ## ref: https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html
    ## e.g:#
    ## pgHbaConfiguration: |-
    ##   local all all trust
    ##   host all all localhost trust
    ##   host mydatabase mysuser 192.168.0.0/24 md5
    ##
    pgHbaConfiguration: ""
    ## PostgreSQL Primary service configuration
    ##
    service:
      enabled: true
      type: ClusterIP
      ports:
        postgresql: 5432
    ## PostgreSQL Primary persistence configuration
    ##
    persistence:
      enabled: true
      # volumeName and existingClaim must be set together to use existing PVC
      volumeName: postgresql
      existingClaim: postgresql
      mountPath: /bitnami/postgresql
      subPath: ""
      storageClass: local-hostpath
      accessModes:
        - ReadWriteOnce
      # size: 8Gi

  ## @section PostgreSQL read only replica parameters (only used when `architecture` is set to `replication`)
  ##
  readReplicas:
    name: read
    replicaCount: 1
    ## PostgreSQL Primary service configuration
    ##
    service:
      enabled: true
      type: ClusterIP
      ports:
        postgresql: 5432
    ## PostgreSQL read only persistence configuration
    ##
    persistence:
      enabled: true
      # volumeName and existingClaim must be set together to use existing PVC
      volumeName: postgresql-read
      existingClaim: postgresql-read
      mountPath: /bitnami/postgresql
      subPath: ""
      storageClass: local-hostpath
      accessModes:
        - ReadWriteOnce
      # size: 8Gi

  ## @section Password update job
  ##
  passwordUpdateJob:
    enabled: false

  backup:
    enabled: false

  serviceAccount:
    create: true
    name: ""
    automountServiceAccountToken: false

  metrics:
    enabled: true

  serviceMonitor:
    enabled: false

  prometheusRule:
    enabled: false
