---
apiVersion: v1
kind: Secret
metadata:
  name: pgpassfile
type: Opaque
stringData:
  # https://www.postgresql.org/docs/9.4/libpq-pgpass.html
  pgpassfile: |
    {{- .Values.pgpass.value | nindent 4 }}
