volumes:
  wwwDir: 
    hostPath: /Users/jimtang/Development/vol/nginx/www
  configDir: 
    hostPath: /Users/jimtang/Development/vol/nginx/internal/conf.d
  config:
    hostPath: /Users/jimtang/Development/vol/nginx/internal/nginx.conf

httproute:
  enabled: true
  parentRefs:
  - name: envoy-localhost
    namespace: default
    sectionName: https
    port: 8443
  - name: envoy-localhost
    namespace: default
    sectionName: http
    port: 8080
  hostnames:
  - nginx.localhost
  - localhost
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    filters: []
    backendRefs:
    - name: nginx-internal
      namespace: internal
      port: 80
      weight: 1
  