---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/keep-policy: keep
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volumes.pgdata.storageClass }}
  hostPath:
    path: {{ .Values.volumes.pgdata.hostPath }}
    type: DirectoryOrCreate
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ include "chart.fullname" . }}
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ .Values.volumes.pgdata.storageClass }}
