apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cert-manager-bootstrap
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 6
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-cert-manager-bootstrap
      restartPolicy: OnFailure
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -ec
        - |
          CM_NS="{{ .Release.Namespace }}"
          TIMEOUT=60s

          kubectl wait --for=condition=Available=True deployment/cert-manager -n "${CM_NS}" --timeout=$TIMEOUT
          kubectl wait --for=condition=Available=True deployment/cert-manager-webhook -n "${CM_NS}" --timeout=$TIMEOUT
          kubectl wait --for=condition=Available=True deployment/cert-manager-cainjector -n "${CM_NS}" --timeout=$TIMEOUT || true

          cat <<'EOF' | kubectl apply -f -
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: localhost
          spec:
            ca:
              secretName: mkcert-ca-key-pair
          ---
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: localhost-tls-cert
            namespace: {{ .Release.Namespace }}
          spec:
            secretName: localhost-tls-cert
            duration: 8760h
            renewBefore: 720h
            commonName: localhost
            dnsNames:
            - 127.0.0.1
            - ::1
            - localhost
            - nginx.localhost
            - audiobook.localhost
            - torrent.localhost
            - jackett.localhost
            - headlamp.localhost
            - keycloak.localhost
            - flux.localhost
            - elasticsearch.localhost
            - kibana.localhost
            - grafana.localhost
            - alertmanager.localhost
            - prometheus.localhost
            - logstash.localhost
            - argocd.localhost
            - mail.localhost
            issuerRef:
              name: localhost
              kind: ClusterIssuer
              group: cert-manager.io
          EOF

---
