apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secret.basicAuth.user | b64enc }}
  password: {{ .Values.secret.basicAuth.password | b64enc }}
