apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cert-manager-bootstrap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-cert-manager-bootstrap
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get","list","watch"]
- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers"]
  verbs: ["get","list","watch","create","update","patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cert-manager-bootstrap
  labels:
    {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-cert-manager-bootstrap
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-cert-manager-bootstrap
  namespace: {{ .Release.Namespace }}

---