apiVersion: v2
name: qbt
description: A chart for qbt server
type: application
version: 0.0.1
appVersion: "5.2.3"

home: https://github.com/jimtang2/helm-charts/tree/main/charts/qbt
sources:
  - https://github.com/qbittorrent/qBittorrent/
maintainers:
  - name: jimtang2
    url: https://github.com/jimtang2