apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ include "chart.fullname" . }}-lab9-studio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    hostname: "lab9.studio"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  telemetry:
    metrics:
      prometheus:
        disable: false
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        name: {{ include "chart.fullname" . }}-lab9-studio
        labels:
          hostname: "lab9.studio"

---
