apiVersion: v2
name: cert-manager
description: cert-manager
type: application
version: 0.1.0
appVersion: "v1.21.0"
dependencies:
  - name: cert-manager
    version: "v1.21.0"
    repository: oci://quay.io/jetstack/charts
    condition: cert-manager.enabled
