logLevel: debug

env:
- name: ES_USER
  value: elastic
- name: ES_PASSWORD
  valueFrom:
    secretKeyRef:
      name: elasticsearch-es-elastic-user
      key: elastic

extraVolumes:
- name: fluentbit-state
  hostPath: 
    path: /Users/jimtang/Development/vol/fluent-bit/state
    type: DirectoryOrCreate
- name: es-ca
  secret:
    secretName: elasticsearch-es-http-certs-public

extraVolumeMounts:
- name: fluentbit-state
  mountPath: /fluent-bit/state
- name: es-ca
  mountPath: /fluent-bit/tls
  readOnly: true

config:
  service: |
    [SERVICE]
      Daemon Off
      Flush {{ .Values.flush | default "1" }}
      Log_Level {{ .Values.logLevel | default "info" }}
      Parsers_File /fluent-bit/etc/parsers.conf
      Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port  {{ .Values.metricsPort | default "2020" }}
      Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs    
  inputs: |
    [INPUT]
      Name tail
      Path /var/log/containers/*.log
      Exclude_Path /var/log/containers/fluent-bit*
      Parser cri
      Tag kube.*
      Mem_Buf_Limit 50MB
      Skip_Long_Lines On
      Refresh_Interval 5
      DB /fluent-bit/state/flb.db

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On
  
    [FILTER]
      Name parser
      Match kube.var.log.containers.nginx*
      Key_Name log
      Parser nginx_access
      Reserve_Data On
      Preserve_Key Off
    
    [FILTER]
      Name parser
      Match kube.var.log.containers.envoy*
      Key_Name log
      Parser envoy_access
      Reserve_Data On
      Preserve_Key Off

  ## https://docs.fluentbit.io/manual/pipeline/outputs    
  outputs: |
    [OUTPUT]
      Name es
      Match kube.*
      Host elasticsearch-es-http
      Port 9200
      HTTP_User ${ES_USER}
      HTTP_Passwd ${ES_PASSWORD}
      TLS On
      TLS.Verify On
      TLS.CA_File /fluent-bit/tls/ca.crt
      Logstash_Format On
      Logstash_Prefix fluent-bit
      Suppress_Type_Name On
      Replace_Dots On
      Retry_Limit 5
      Trace_Error On
    
  customParsers: |
    [PARSER]
      Name nginx_access
      Format json
      Time_Key time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
      Time_Keep On
  
    [PARSER]
      Name envoy_access
      Format json
      Time_Key start_time
      Time_Format %Y-%m-%dT%H:%M:%S.%LZ
      Time_Keep On
