qbittorrent:
  image:
    repository: linuxserver/qbittorrent
    tag: "5.2.3"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi
  env: []
  volumes:
    config:
      hostPath: ""
    downloads:
      hostPath: ""
  service:
    enabled: true
    type: ClusterIP
    ports:
      webui:
        port: 8080
        targetPort: 8080
        protocol: TCP
      torrent_tcp:
        port: 6881
        targetPort: 6881
        protocol: TCP
      torrent_udp:
        port: 6881
        targetPort: 6881
        protocol: UDP
  httproute:
    enabled: true

jackett:
  image:
    repository: linuxserver/jackett
    tag: "0.24.2237"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  volumes:
    config:
      hostPath: ""
    downloads:
      hostPath: ""
  env: []
  service:
    enabled: true
    type: ClusterIP
    ports:
      webui:
        port: 9117
        targetPort: 9117
        protocol: TCP
  httproute:
    enabled: true