apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-cleanup"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: "{{ .Release.Name }}-cleanup"
      restartPolicy: Never
      containers:
      - name: cleanup
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          NAMESPACE="{{ .Release.Namespace }}"
          SELECTOR="app.kubernetes.io/instance={{ .Release.Name }}"
          RESOURCES=gateway,envoyproxy,service,serviceaccount,role

          kubectl get $RESOURCES -n $NAMESPACE -l $SELECTOR --ignore-not-found -o name | xargs kubectl delete -n $NAMESPACE

          while true; do
            output=$(kubectl get $RESOURCES -l $SELECTOR -n $NAMESPACE -o name)
            if [ ${#output} -eq 0 ]; then 
              break
            else
              echo "${#output}"
              sleep 0.5
            fi
          done


        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
      activeDeadlineSeconds: 30

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-cleanup"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-cleanup"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways"]
  verbs: ["list", "delete"]
- apiGroups: ["gateway.envoyproxy.io"]
  resources: ["envoyproxies"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["services", "serviceaccounts"]
  verbs: ["list", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-cleanup"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-cleanup"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-cleanup"
  apiGroup: rbac.authorization.k8s.io